### PR TITLE
added time from 1st kernel to last kernel in --profiling

### PR DESCRIPTION
**Pull request by kjatkows**

### CODE REVIEW

**Comment by kjatkows** [comment]
image
q 10

image
q 100

**Comment by leszczyn** [comment]
> 

is this for q100 s100 or just q100 (w need to check the same s and q values >1 
compare original driver vs our

**Comment by kjatkows** [comment]
> > 
> 
> is this for q100 s100 or just q100 (w need to check the same s and q values >1 compare original driver vs our

this is q100 s1

**Comment by leszczyn** [comment]
> > > 
> > 
> > 
> > is this for q100 s100 or just q100 (w need to check the same s and q values >1 compare original driver vs our
> 
> this is q100 s1

we dont need it :) please prepare comparsion for q2 s2, q4 s4, q10 s10, q50 s50, single ccs execution (you can just force this in app in zenon.cpp (ccs_id = 0;// ( zenon_cntr++ ) % command_queue_count;)

**Review by mpenkows — APPROVED** [review]

**Pull request merged**
