### PR TITLE
fixed bug in total GPU time

### PR DESCRIPTION
**Pull request by kjatkows**
Now end time of total GPU time is at the end of the last kernel.

### CODE REVIEW

**Comment by tponieck** [comment]
@kjatkows  it isn't good change. Total gpu time cannot be measured on CPU. it is time computed from kernel profiling but following this formula:
last_kernel.end_time - first_kernel.start time

**Comment by mpenkows** [comment]
Could you upload some example of the current output from profiling?

**Comment by kjatkows** [comment]
> Could you upload some example of the current output from profiling?

image

**Comment by mpenkows** [comment]
Please change the Total GPU time to be displayed also as min, max and average as it is for total kernels time.

**Comment by kjatkows** [comment]
image
output

**Comment by kjatkows** [comment]
Output:

image

**Pull request merged**
